feat(testing-auth): add unit tests for applicationconfig class
Triple-A-Unibuc/service pull request #12
Opened 2024-03-21 09:43 UTC by nicugnm

Features:
- Add unit tests for every auth class.

2024-03-27 20:48 UTC, RaduADumitru requested changes
Nice approach for the tests themselves, but please do a merge from main before merging the PR, and ensure there are no conflicts in configuration and everything works fine after - some aspects would be duplicated, like adding Junit which we've done in the meantime

2024-03-27 20:48 UTC, RaduADumitru commented on src/test/java/ro/unibuc/triplea/infrastructure/auth/fixtures/TokenFixtures.java
> +        return new Token(1, token, TokenType.BEARER, false, false, UserFixtures.user("username"));
Good approach of using text fixtures, I learned something new today

2024-03-27 20:48 UTC, RaduADumitru commented on gradle/wrapper/gradle-wrapper.properties
>  networkTimeout=10000
Could conflict with config changes on main

2024-03-27 20:48 UTC, RaduADumitru commented on build.gradle
> +	useJUnitPlatform()
Could conflict with config changes on main; junit was also added there

2024-03-27 20:48 UTC, RaduADumitru commented on build.gradle
> +	testImplementation 'org.projectlombok:lombok:1.18.28'
Could conflict with config changes on main

2024-03-27 20:52 UTC, nicugnm commented
Merge with main is already done, check commits

2024-03-27 21:10 UTC, nicugnm commented on gradle/wrapper/gradle-wrapper.properties
>  networkTimeout=10000
rollbacked

2024-03-28 07:17 UTC, RaduADumitru approved these changes
LGTM

2024-03-28 07:18 UTC, merged